version: '2.0'

services:
  terraria:
    container_name: terraria
    build: .
    environment:
      PUID: "12345"
      PGID: "12345"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    volumes:
      - ./world:/world
      - ./config:/config