version: '3.0'

services:
  terraria:
    container_name: terraria
    image: ryshe/terraria:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment: 
      - "WORLD_FILENAME=Baldurun.wld"
    ports:
      - 21050:7777
    volumes:
      - ./world:/root/.local/share/Terraria/Worlds