version: '2.0'

services:
  terraria:
    container_name: terraria
    image: generalmine/terraria-docker
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    volumes:
      - ./world:/world
      - ./config:/config