version: '2.0'

services:
  terraria:
    container_name: terraria
    image: generalmine/terraria-docker
    environment:
      PUID: "<PROCESS UID>"
      PGID: "<PROCESS GID>"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    volumes:
      - <PATH TO WORLDS>:/world
      - <PATH TO CONFIG>:/config